package dss

import (
	"fmt"
	"strings"
	"unicode"
)

// ReactGeneratorOptions configures TypeScript output.
type ReactGeneratorOptions struct {
	// IncludeJSDoc adds JSDoc comments from descriptions
	IncludeJSDoc bool

	// ExportStyle: "named" (export interface), "default" (export default)
	ExportStyle string

	// IncludeVariantUnions generates union types for variants
	IncludeVariantUnions bool

	// BasePropsInterface name to extend (e.g., "HTMLAttributes<HTMLButtonElement>")
	BasePropsInterface string
}

// DefaultReactOptions returns sensible defaults.
func DefaultReactOptions() ReactGeneratorOptions {
	return ReactGeneratorOptions{
		IncludeJSDoc:         true,
		ExportStyle:          "named",
		IncludeVariantUnions: true,
		BasePropsInterface:   "",
	}
}

// GenerateReactTypes generates TypeScript interfaces for all components.
func (ds *DesignSystem) GenerateReactTypes(opts ReactGeneratorOptions) (string, error) {
	if len(ds.Components) == 0 {
		return "", fmt.Errorf("design system has no components defined")
	}

	var b strings.Builder

	// Header
	b.WriteString("/**\n")
	b.WriteString(fmt.Sprintf(" * %s - Component Types\n", ds.Meta.Name))
	if ds.Meta.Version != "" {
		b.WriteString(fmt.Sprintf(" * Version: %s\n", ds.Meta.Version))
	}
	b.WriteString(" * Generated by systemspec-designsystem\n")
	b.WriteString(" */\n\n")

	// Generate types for each component
	for i, comp := range ds.Components {
		if i > 0 {
			b.WriteString("\n")
		}
		generateComponentTypes(&b, comp, opts)
	}

	return b.String(), nil
}

// GenerateComponentTypes generates TypeScript for a single component.
func (c *Component) GenerateTypes(opts ReactGeneratorOptions) string {
	var b strings.Builder
	generateComponentTypes(&b, *c, opts)
	return b.String()
}

func generateComponentTypes(b *strings.Builder, c Component, opts ReactGeneratorOptions) {
	interfaceName := pascalCase(c.ID) + "Props"

	// Generate variant union type if variants exist
	if opts.IncludeVariantUnions && len(c.Variants) > 0 {
		variantTypeName := pascalCase(c.ID) + "Variant"
		if opts.IncludeJSDoc {
			b.WriteString(fmt.Sprintf("/** Available variants for %s */\n", c.Name))
		}
		b.WriteString(fmt.Sprintf("export type %s = ", variantTypeName))

		variants := make([]string, len(c.Variants))
		for i, v := range c.Variants {
			variants[i] = fmt.Sprintf("'%s'", v.ID)
		}
		b.WriteString(strings.Join(variants, " | "))
		b.WriteString(";\n\n")
	}

	// Generate size union if size prop exists
	for _, prop := range c.Props {
		if prop.Name == "size" && len(prop.EnumValues) > 0 {
			sizeTypeName := pascalCase(c.ID) + "Size"
			if opts.IncludeJSDoc {
				b.WriteString(fmt.Sprintf("/** Available sizes for %s */\n", c.Name))
			}
			b.WriteString(fmt.Sprintf("export type %s = ", sizeTypeName))

			sizes := make([]string, len(prop.EnumValues))
			for i, s := range prop.EnumValues {
				sizes[i] = fmt.Sprintf("'%s'", s)
			}
			b.WriteString(strings.Join(sizes, " | "))
			b.WriteString(";\n\n")
			break
		}
	}

	// JSDoc for main interface
	if opts.IncludeJSDoc {
		b.WriteString("/**\n")
		b.WriteString(fmt.Sprintf(" * Props for the %s component.\n", c.Name))
		if c.Description != "" {
			b.WriteString(fmt.Sprintf(" * %s\n", c.Description))
		}
		if c.LLM != nil {
			if c.LLM.Intent != "" {
				b.WriteString(fmt.Sprintf(" * @purpose %s\n", c.LLM.Intent))
			}
			if len(c.LLM.AllowedContexts) > 0 {
				b.WriteString(fmt.Sprintf(" * @contexts %s\n", strings.Join(c.LLM.AllowedContexts, ", ")))
			}
		}
		b.WriteString(" */\n")
	}

	// Interface declaration
	b.WriteString(fmt.Sprintf("export interface %s", interfaceName))
	if opts.BasePropsInterface != "" {
		b.WriteString(fmt.Sprintf(" extends %s", opts.BasePropsInterface))
	}
	b.WriteString(" {\n")

	// Props
	for _, prop := range c.Props {
		writeProp(b, prop, c, opts)
	}

	// Slots as children/render props
	for _, slot := range c.Slots {
		writeSlot(b, slot, opts)
	}

	b.WriteString("}\n")

	// Generate state enum if states are defined
	if len(c.States) > 0 {
		b.WriteString("\n")
		stateTypeName := pascalCase(c.ID) + "State"
		if opts.IncludeJSDoc {
			b.WriteString(fmt.Sprintf("/** Interactive states for %s */\n", c.Name))
		}
		b.WriteString(fmt.Sprintf("export type %s = ", stateTypeName))

		states := make([]string, len(c.States))
		for i, s := range c.States {
			states[i] = fmt.Sprintf("'%s'", s.ID)
		}
		b.WriteString(strings.Join(states, " | "))
		b.WriteString(";\n")
	}
}

func writeProp(b *strings.Builder, prop Prop, comp Component, opts ReactGeneratorOptions) {
	// JSDoc comment
	if opts.IncludeJSDoc && prop.Description != "" {
		b.WriteString(fmt.Sprintf("  /** %s */\n", prop.Description))
	}

	// Prop name with optional marker
	b.WriteString(fmt.Sprintf("  %s", prop.Name))
	if !prop.Required {
		b.WriteString("?")
	}
	b.WriteString(": ")

	// Type
	tsType := mapPropType(prop, comp)
	b.WriteString(tsType)
	b.WriteString(";\n")
}

func writeSlot(b *strings.Builder, slot Slot, opts ReactGeneratorOptions) {
	if opts.IncludeJSDoc && slot.Description != "" {
		b.WriteString(fmt.Sprintf("  /** %s */\n", slot.Description))
	}

	// Convert slot name to prop name
	propName := slot.Name
	if propName == "default" {
		propName = "children"
	}

	b.WriteString(fmt.Sprintf("  %s", propName))
	if !slot.Required {
		b.WriteString("?")
	}
	b.WriteString(": React.ReactNode;\n")
}

func mapPropType(prop Prop, comp Component) string {
	switch prop.Type {
	case "string":
		return "string"
	case "number":
		return "number"
	case "boolean":
		return "boolean"
	case "enum":
		if len(prop.EnumValues) > 0 {
			// Check if this is the variant prop
			if prop.Name == "variant" {
				return pascalCase(comp.ID) + "Variant"
			}
			if prop.Name == "size" {
				return pascalCase(comp.ID) + "Size"
			}
			// Inline union for other enums
			values := make([]string, len(prop.EnumValues))
			for i, v := range prop.EnumValues {
				values[i] = fmt.Sprintf("'%s'", v)
			}
			return strings.Join(values, " | ")
		}
		return "string"
	case "function":
		return "() => void"
	case "object":
		return "Record<string, unknown>"
	case "array":
		return "unknown[]"
	case "node", "element", "ReactNode":
		return "React.ReactNode"
	default:
		return "unknown"
	}
}

func pascalCase(s string) string {
	if s == "" {
		return ""
	}

	var result strings.Builder
	capitalizeNext := true

	for _, r := range s {
		if r == '-' || r == '_' || r == ' ' {
			capitalizeNext = true
			continue
		}

		if capitalizeNext {
			result.WriteRune(unicode.ToUpper(r))
			capitalizeNext = false
		} else {
			result.WriteRune(r)
		}
	}

	return result.String()
}
