package dss

import (
	"fmt"
	"strings"
)

// D2Options configures D2 diagram output.
type D2Options struct {
	// Direction: "right", "down", "left", "up"
	Direction string

	// ShowTokens includes token relationships
	ShowTokens bool

	// ShowEvents includes event flow
	ShowEvents bool

	// ShowSlots includes slot composition
	ShowSlots bool

	// ShowProps includes property lists
	ShowProps bool

	// GroupByCategory groups components by category
	GroupByCategory bool

	// Theme: "default", "neutral", "earth", "terminal", etc.
	Theme string

	// Sketch mode for hand-drawn look
	Sketch bool
}

// DefaultD2Options returns sensible defaults.
func DefaultD2Options() D2Options {
	return D2Options{
		Direction:       "right",
		ShowTokens:      false,
		ShowEvents:      true,
		ShowSlots:       true,
		ShowProps:       true,
		GroupByCategory: true,
		Theme:           "",
		Sketch:          false,
	}
}

// GenerateD2 generates a D2 diagram showing component relationships.
// D2 is a modern diagram scripting language: https://d2lang.com/
func (ds *DesignSystem) GenerateD2(opts D2Options) (string, error) {
	if len(ds.Components) == 0 {
		return "", fmt.Errorf("design system has no components defined")
	}

	var b strings.Builder

	// Header comment
	b.WriteString("# ")
	b.WriteString(ds.Meta.Name)
	if ds.Meta.Version != "" {
		b.WriteString(" v")
		b.WriteString(ds.Meta.Version)
	}
	b.WriteString(" - Component Architecture\n")
	b.WriteString("# Generated by systemspec-designsystem\n\n")

	// Global direction
	if opts.Direction != "" {
		b.WriteString("direction: ")
		b.WriteString(opts.Direction)
		b.WriteString("\n\n")
	}

	// Style configuration
	if opts.Sketch {
		b.WriteString("style.sketch: true\n\n")
	}

	// Build component ID mapping
	nodeIDs := make(map[string]string)
	for _, c := range ds.Components {
		nodeIDs[c.ID] = sanitizeD2ID(c.ID)
	}

	// Group by category if enabled
	if opts.GroupByCategory {
		categories := make(map[string][]Component)
		for _, c := range ds.Components {
			cat := c.Category
			if cat == "" {
				cat = "other"
			}
			categories[cat] = append(categories[cat], c)
		}

		for cat, components := range categories {
			catID := sanitizeD2ID(cat)
			b.WriteString(fmt.Sprintf("%s: %s {\n", catID, formatD2Label(cat)))
			b.WriteString("  style.fill: \"#f8fafc\"\n")
			b.WriteString("  style.stroke: \"#e2e8f0\"\n\n")

			for _, c := range components {
				writeD2ComponentNode(&b, c, opts, "  ")
			}
			b.WriteString("}\n\n")
		}
	} else {
		// Write all components without grouping
		for _, c := range ds.Components {
			writeD2ComponentNode(&b, c, opts, "")
		}
		b.WriteString("\n")
	}

	// Write relationships
	b.WriteString("# Relationships\n")
	for _, c := range ds.Components {
		nodeID := nodeIDs[c.ID]
		if opts.GroupByCategory && c.Category != "" {
			nodeID = sanitizeD2ID(c.Category) + "." + nodeID
		}

		// Uses relationships (explicit dependencies)
		for _, usedID := range c.Uses {
			targetID := nodeIDs[usedID]
			// Find target's category for full path
			for _, tc := range ds.Components {
				if tc.ID == usedID && opts.GroupByCategory && tc.Category != "" {
					targetID = sanitizeD2ID(tc.Category) + "." + targetID
					break
				}
			}
			b.WriteString(fmt.Sprintf("%s -> %s: uses\n", nodeID, targetID))
		}

		// Slot relationships (composition)
		if opts.ShowSlots {
			for _, slot := range c.Slots {
				for _, allowedID := range slot.AllowedComponents {
					targetID := nodeIDs[allowedID]
					for _, tc := range ds.Components {
						if tc.ID == allowedID && opts.GroupByCategory && tc.Category != "" {
							targetID = sanitizeD2ID(tc.Category) + "." + targetID
							break
						}
					}
					b.WriteString(fmt.Sprintf("%s -> %s: slot(%s) {\n", nodeID, targetID, slot.Name))
					b.WriteString("  style.stroke-dash: 3\n")
					b.WriteString("}\n")
				}
			}
		}

		// Constraint: Required parent
		if c.Constraints != nil && c.Constraints.RequiredParent != "" {
			parentID := nodeIDs[c.Constraints.RequiredParent]
			for _, tc := range ds.Components {
				if tc.ID == c.Constraints.RequiredParent && opts.GroupByCategory && tc.Category != "" {
					parentID = sanitizeD2ID(tc.Category) + "." + parentID
					break
				}
			}
			b.WriteString(fmt.Sprintf("%s -> %s: contains {\n", parentID, nodeID))
			b.WriteString("  style.stroke: \"#22c55e\"\n")
			b.WriteString("}\n")
		}
	}

	// Pattern relationships
	if len(ds.Patterns) > 0 {
		b.WriteString("\n# Patterns\n")
		b.WriteString("patterns: Patterns {\n")
		b.WriteString("  style.fill: \"#fef3c7\"\n")
		b.WriteString("  style.stroke: \"#f59e0b\"\n\n")

		for _, p := range ds.Patterns {
			patternID := sanitizeD2ID(p.ID)
			b.WriteString(fmt.Sprintf("  %s: %s {\n", patternID, p.Name))
			b.WriteString("    shape: hexagon\n")
			if p.Description != "" {
				// Truncate long descriptions
				desc := p.Description
				if len(desc) > 50 {
					desc = desc[:47] + "..."
				}
				b.WriteString(fmt.Sprintf("    tooltip: \"%s\"\n", escapeD2String(desc)))
			}
			b.WriteString("  }\n")
		}
		b.WriteString("}\n\n")

		// Pattern -> Component relationships
		for _, p := range ds.Patterns {
			patternID := "patterns." + sanitizeD2ID(p.ID)
			for _, pc := range p.Components {
				targetID := nodeIDs[pc.ComponentID]
				for _, tc := range ds.Components {
					if tc.ID == pc.ComponentID && opts.GroupByCategory && tc.Category != "" {
						targetID = sanitizeD2ID(tc.Category) + "." + targetID
						break
					}
				}
				label := pc.Role
				if label == "" {
					label = "uses"
				}
				b.WriteString(fmt.Sprintf("%s -> %s: %s {\n", patternID, targetID, label))
				b.WriteString("  style.stroke-dash: 5\n")
				b.WriteString("  style.stroke: \"#f59e0b\"\n")
				b.WriteString("}\n")
			}
		}
	}

	return b.String(), nil
}

// GenerateD2ComponentDiagram generates a focused D2 diagram for a single component.
func (ds *DesignSystem) GenerateD2ComponentDiagram(componentID string, opts D2Options) (string, error) {
	// Find the component
	var target *Component
	for i := range ds.Components {
		if ds.Components[i].ID == componentID {
			target = &ds.Components[i]
			break
		}
	}
	if target == nil {
		return "", fmt.Errorf("component %q not found", componentID)
	}

	var b strings.Builder

	b.WriteString("# ")
	b.WriteString(target.Name)
	b.WriteString(" Component Diagram\n\n")

	if opts.Direction != "" {
		b.WriteString("direction: ")
		b.WriteString(opts.Direction)
		b.WriteString("\n\n")
	}

	nodeID := sanitizeD2ID(target.ID)

	// Main component with details
	b.WriteString(fmt.Sprintf("%s: %s {\n", nodeID, target.Name))
	b.WriteString("  style.fill: \"#3b82f6\"\n")
	b.WriteString("  style.font-color: \"#ffffff\"\n")
	b.WriteString("  style.bold: true\n")

	// Props as nested items
	if opts.ShowProps && len(target.Props) > 0 {
		b.WriteString("\n  props: Props {\n")
		b.WriteString("    style.fill: \"#f1f5f9\"\n")
		for _, p := range target.Props {
			propID := sanitizeD2ID(p.Name)
			required := ""
			if p.Required {
				required = " *"
			}
			b.WriteString(fmt.Sprintf("    %s: \"%s: %s%s\"\n", propID, p.Name, p.Type, required))
		}
		b.WriteString("  }\n")
	}

	// Events as nested items
	if opts.ShowEvents && len(target.Events) > 0 {
		b.WriteString("\n  events: Events {\n")
		b.WriteString("    style.fill: \"#fef3c7\"\n")
		for _, e := range target.Events {
			evtID := sanitizeD2ID(e.Name)
			b.WriteString(fmt.Sprintf("    %s: \"%s\"\n", evtID, e.Name))
		}
		b.WriteString("  }\n")
	}

	// Slots as nested items
	if opts.ShowSlots && len(target.Slots) > 0 {
		b.WriteString("\n  slots: Slots {\n")
		b.WriteString("    style.fill: \"#dcfce7\"\n")
		for _, s := range target.Slots {
			slotID := sanitizeD2ID(s.Name)
			b.WriteString(fmt.Sprintf("    %s: \"%s\"\n", slotID, s.Name))
		}
		b.WriteString("  }\n")
	}

	b.WriteString("}\n\n")

	// Dependencies
	if len(target.Uses) > 0 {
		b.WriteString("# Dependencies\n")
		for _, usedID := range target.Uses {
			usedNode := sanitizeD2ID(usedID)
			b.WriteString(fmt.Sprintf("%s: %s {\n", usedNode, usedID))
			b.WriteString("  style.fill: \"#e2e8f0\"\n")
			b.WriteString("}\n")
			b.WriteString(fmt.Sprintf("%s -> %s: depends on\n", nodeID, usedNode))
		}
		b.WriteString("\n")
	}

	// Allowed slot components
	if opts.ShowSlots {
		slotTargets := make(map[string][]string)
		for _, slot := range target.Slots {
			for _, allowedID := range slot.AllowedComponents {
				slotTargets[allowedID] = append(slotTargets[allowedID], slot.Name)
			}
		}
		if len(slotTargets) > 0 {
			b.WriteString("# Slot Targets\n")
			for compID, slots := range slotTargets {
				compNode := sanitizeD2ID(compID)
				b.WriteString(fmt.Sprintf("%s: %s\n", compNode, compID))
				b.WriteString(fmt.Sprintf("%s.slots -> %s: can contain {\n", nodeID, compNode))
				b.WriteString("  style.stroke-dash: 3\n")
				b.WriteString(fmt.Sprintf("  tooltip: \"slots: %s\"\n", strings.Join(slots, ", ")))
				b.WriteString("}\n")
			}
		}
	}

	return b.String(), nil
}

// Helper functions

func writeD2ComponentNode(b *strings.Builder, c Component, _ D2Options, indent string) {
	nodeID := sanitizeD2ID(c.ID)

	b.WriteString(fmt.Sprintf("%s%s: %s {\n", indent, nodeID, c.Name))

	// Shape based on category
	shape := getD2Shape(c)
	if shape != "" {
		b.WriteString(fmt.Sprintf("%s  shape: %s\n", indent, shape))
	}

	// Tooltip with description
	if c.Description != "" {
		desc := c.Description
		if len(desc) > 100 {
			desc = desc[:97] + "..."
		}
		b.WriteString(fmt.Sprintf("%s  tooltip: \"%s\"\n", indent, escapeD2String(desc)))
	}

	// Link to documentation
	if c.DocumentationURL != "" {
		b.WriteString(fmt.Sprintf("%s  link: %s\n", indent, c.DocumentationURL))
	}

	b.WriteString(fmt.Sprintf("%s}\n", indent))
}

func getD2Shape(c Component) string {
	switch c.Category {
	case "inputs", "input", "form":
		return "parallelogram"
	case "layout", "container":
		return "rectangle"
	case "feedback", "notification":
		return "oval"
	case "navigation", "nav":
		return "page"
	default:
		return ""
	}
}

func sanitizeD2ID(id string) string {
	// D2 IDs can contain most characters but some need escaping
	// Replace problematic characters
	replacer := strings.NewReplacer(
		" ", "_",
		".", "_",
		"/", "_",
		":", "_",
	)
	return replacer.Replace(id)
}

func formatD2Label(s string) string {
	// Convert to title case for display
	words := strings.Split(strings.ReplaceAll(s, "-", " "), " ")
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}

func escapeD2String(s string) string {
	// Escape quotes and newlines for D2 strings
	replacer := strings.NewReplacer(
		"\"", "\\\"",
		"\n", " ",
		"\r", "",
	)
	return replacer.Replace(s)
}
