package dss

import (
	"fmt"
	"sort"
	"strings"
)

// CSSGeneratorOptions configures CSS output format.
type CSSGeneratorOptions struct {
	// Format specifies output format: "tailwind4" (default), "css-vars", "scss"
	Format string

	// Prefix for CSS variable names (e.g., "pm" → "--pm-color-primary")
	Prefix string

	// IncludeComments adds usage descriptions as CSS comments
	IncludeComments bool

	// IncludeDarkMode is deprecated and has no effect: mode-override blocks
	// are emitted whenever the document declares modes or tokens carry
	// per-mode values.
	//
	// Deprecated: mode emission is data-driven.
	IncludeDarkMode bool
}

// DefaultCSSOptions returns sensible defaults for CSS generation.
func DefaultCSSOptions() CSSGeneratorOptions {
	return CSSGeneratorOptions{
		Format:          "tailwind4",
		Prefix:          "",
		IncludeComments: true,
		IncludeDarkMode: false,
	}
}

// GenerateCSS generates CSS custom properties from the design system foundations.
func (ds *DesignSystem) GenerateCSS(opts CSSGeneratorOptions) (string, error) {
	if ds.Foundations.isEmpty() {
		return "", fmt.Errorf("design system has no foundations defined")
	}

	var b strings.Builder

	switch opts.Format {
	case "tailwind4":
		return ds.generateTailwind4CSS(opts, &b)
	case "css-vars":
		return ds.generateCSSVars(opts, &b)
	case "scss":
		return ds.generateSCSS(opts, &b)
	case "mkdocs-material":
		return ds.generateMkDocsMaterialCSS(opts, &b)
	default:
		return ds.generateTailwind4CSS(opts, &b)
	}
}

// generateTailwind4CSS generates Tailwind v4 @theme block format.
func (ds *DesignSystem) generateTailwind4CSS(opts CSSGeneratorOptions, b *strings.Builder) (string, error) {
	f := ds.Foundations

	// Header comment
	b.WriteString("/* ")
	b.WriteString(ds.Meta.Name)
	if ds.Meta.Version != "" {
		b.WriteString(" v")
		b.WriteString(ds.Meta.Version)
	}
	b.WriteString(" - Generated by systemspec-designsystem */\n\n")

	b.WriteString("@import \"tailwindcss\";\n\n")
	b.WriteString("@theme {\n")

	// Colors
	if len(f.Colors) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Colors */\n")
		}
		for _, c := range f.Colors {
			writeColorToken(b, c, opts)
		}
		b.WriteString("\n")
	}

	// Typography - Font Families
	if f.Typography != nil && len(f.Typography.FontFamilies) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Font Families */\n")
		}
		for _, ff := range f.Typography.FontFamilies {
			writeFontFamily(b, ff, opts)
		}
		b.WriteString("\n")
	}

	// Typography - Font Sizes
	if f.Typography != nil && len(f.Typography.FontSizes) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Font Sizes */\n")
		}
		for _, fs := range f.Typography.FontSizes {
			writeFontSize(b, fs, opts)
		}
		b.WriteString("\n")
	}

	// Typography - Font Weights
	if f.Typography != nil && len(f.Typography.FontWeights) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Font Weights */\n")
		}
		for _, fw := range f.Typography.FontWeights {
			writeFontWeight(b, fw, opts)
		}
		b.WriteString("\n")
	}

	// Typography - Line Heights
	if f.Typography != nil && len(f.Typography.LineHeights) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Line Heights */\n")
		}
		for _, lh := range f.Typography.LineHeights {
			writeLineHeight(b, lh, opts)
		}
		b.WriteString("\n")
	}

	// Spacing
	if f.Spacing != nil && len(f.Spacing.Scale) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Spacing */\n")
		}
		for _, s := range f.Spacing.Scale {
			writeSpacing(b, s, opts)
		}
		b.WriteString("\n")
	}

	// Border Radius
	if len(f.BorderRadius) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Border Radius */\n")
		}
		for _, br := range f.BorderRadius {
			writeBorderRadius(b, br, opts)
		}
		b.WriteString("\n")
	}

	// Elevation/Shadows
	if len(f.Elevation) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Shadows */\n")
		}
		for _, e := range f.Elevation {
			writeElevation(b, e, opts)
		}
		b.WriteString("\n")
	}

	// Motion - Durations
	if f.Motion != nil && len(f.Motion.Durations) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Animation Durations */\n")
		}
		for _, d := range f.Motion.Durations {
			writeDuration(b, d, opts)
		}
		b.WriteString("\n")
	}

	// Motion - Easings
	if f.Motion != nil && len(f.Motion.Easings) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Animation Easings */\n")
		}
		for _, e := range f.Motion.Easings {
			writeEasing(b, e, opts)
		}
		b.WriteString("\n")
	}

	// Breakpoints
	if len(f.Breakpoints) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Breakpoints */\n")
		}
		for _, bp := range f.Breakpoints {
			writeBreakpoint(b, bp, opts)
		}
		b.WriteString("\n")
	}

	// Z-Index
	if len(f.ZIndex) > 0 {
		if opts.IncludeComments {
			b.WriteString("  /* Z-Index Layers */\n")
		}
		for _, z := range f.ZIndex {
			writeZIndex(b, z, opts)
		}
	}

	b.WriteString("}\n")

	// Base styles
	b.WriteString("\n@layer base {\n")
	b.WriteString("  * {\n")
	b.WriteString("    border-color: var(--color-border);\n")
	b.WriteString("  }\n")
	b.WriteString("  body {\n")
	b.WriteString("    background-color: var(--color-background);\n")
	b.WriteString("    color: var(--color-foreground);\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	ds.writeCSSModeBlocks(b, func(id string) string { return "--color-" + normalizeID(id) })
	ds.writeCSSDensityBlocks(b, "", func(id string) string { return "--spacing-" + normalizeID(id) })

	return b.String(), nil
}

// generateCSSVars generates plain CSS custom properties (no Tailwind).
func (ds *DesignSystem) generateCSSVars(opts CSSGeneratorOptions, b *strings.Builder) (string, error) {
	f := ds.Foundations

	b.WriteString("/* ")
	b.WriteString(ds.Meta.Name)
	b.WriteString(" - CSS Custom Properties */\n\n")

	b.WriteString(":root {\n")

	// Colors
	for _, c := range f.Colors {
		varName := cssVarName("color", c.ID, opts.Prefix)
		if opts.IncludeComments && c.Usage != "" {
			b.WriteString(fmt.Sprintf("  /* %s */\n", c.Usage))
		}
		b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, c.Value))
	}

	// Add other token types...
	if f.Spacing != nil {
		for _, s := range f.Spacing.Scale {
			varName := cssVarName("spacing", s.ID, opts.Prefix)
			b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, s.Value))
		}
	}

	for _, br := range f.BorderRadius {
		varName := cssVarName("radius", br.ID, opts.Prefix)
		b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, br.Value))
	}

	b.WriteString("}\n")

	ds.writeCSSModeBlocks(b, func(id string) string { return cssVarName("color", id, opts.Prefix) })
	ds.writeCSSDensityBlocks(b, opts.Prefix, func(id string) string { return cssVarName("spacing", id, opts.Prefix) })

	return b.String(), nil
}

// generateSCSS generates SCSS variables.
func (ds *DesignSystem) generateSCSS(opts CSSGeneratorOptions, b *strings.Builder) (string, error) {
	f := ds.Foundations

	b.WriteString("// ")
	b.WriteString(ds.Meta.Name)
	b.WriteString(" - SCSS Variables\n\n")

	// Colors
	if len(f.Colors) > 0 {
		b.WriteString("// Colors\n")
		for _, c := range f.Colors {
			varName := scssVarName("color", c.ID, opts.Prefix)
			if opts.IncludeComments && c.Usage != "" {
				b.WriteString(fmt.Sprintf("// %s\n", c.Usage))
			}
			b.WriteString(fmt.Sprintf("%s: %s;\n", varName, c.Value))
		}
		b.WriteString("\n")
	}

	// Spacing
	if f.Spacing != nil && len(f.Spacing.Scale) > 0 {
		b.WriteString("// Spacing\n")
		for _, s := range f.Spacing.Scale {
			varName := scssVarName("spacing", s.ID, opts.Prefix)
			b.WriteString(fmt.Sprintf("%s: %s;\n", varName, s.Value))
		}
		b.WriteString("\n")
	}

	// Border Radius
	if len(f.BorderRadius) > 0 {
		b.WriteString("// Border Radius\n")
		for _, br := range f.BorderRadius {
			varName := scssVarName("radius", br.ID, opts.Prefix)
			b.WriteString(fmt.Sprintf("%s: %s;\n", varName, br.Value))
		}
	}

	if modes := ds.collectModes(); len(modes) > 0 {
		b.WriteString("\n// Modes\n")
		for _, mode := range modes {
			for _, c := range f.Colors {
				if v, ok := c.EffectiveModes()[mode]; ok && v != "" {
					b.WriteString(fmt.Sprintf("%s--%s: %s;\n", scssVarName("color", c.ID, opts.Prefix), mode, v))
				}
			}
		}
	}
	if len(f.Densities) > 0 {
		b.WriteString("\n// Densities\n")
		for _, d := range f.Densities {
			b.WriteString(fmt.Sprintf("%s: %v;\n", scssVarName("density", d.ID, opts.Prefix), d.Scale))
		}
	}

	return b.String(), nil
}

// generateMkDocsMaterialCSS generates CSS custom properties for MkDocs Material theme.
func (ds *DesignSystem) generateMkDocsMaterialCSS(opts CSSGeneratorOptions, b *strings.Builder) (string, error) {
	f := ds.Foundations

	// Header comment
	b.WriteString("/**\n")
	b.WriteString(" * ")
	b.WriteString(ds.Meta.Name)
	b.WriteString(" - MkDocs Material Theme\n")
	if ds.Meta.Version != "" {
		b.WriteString(" * Version: ")
		b.WriteString(ds.Meta.Version)
		b.WriteString("\n")
	}
	b.WriteString(" * Generated by systemspec-designsystem\n")
	b.WriteString(" */\n\n")

	// Find key colors by semantic role
	var primaryColor, primaryLight, primaryDark string
	var accentColor, accentLight string
	var bgColor, bgElevated, bgSubtle string
	var fgColor, fgMuted string
	var borderColor, borderSubtle string
	var successColor, warningColor, errorColor string

	for _, c := range f.Colors {
		v := modeValue(c, "dark") // mkdocs-material output is dark-first (slate scheme)
		switch c.ID {
		case "cyan", "primary":
			primaryColor = v
		case "cyan-light", "primary-light":
			primaryLight = v
		case "cyan-dark", "primary-dark":
			primaryDark = v
		case "purple", "secondary", "accent":
			accentColor = v
		case "purple-light", "secondary-light", "accent-light":
			accentLight = v
		case "background":
			bgColor = v
		case "background-elevated":
			bgElevated = v
		case "background-subtle":
			bgSubtle = v
		case "foreground":
			fgColor = v
		case "foreground-muted":
			fgMuted = v
		case "border":
			borderColor = v
		case "border-subtle":
			borderSubtle = v
		case "success":
			successColor = v
		case "warning":
			warningColor = v
		case "error":
			errorColor = v
		}
	}

	// Set defaults if not found
	if primaryColor == "" {
		primaryColor = "#06b6d4"
	}
	if primaryLight == "" {
		primaryLight = "#22d3ee"
	}
	if primaryDark == "" {
		primaryDark = "#0891b2"
	}
	if accentColor == "" {
		accentColor = "#8b5cf6"
	}
	if accentLight == "" {
		accentLight = "#a78bfa"
	}
	if bgColor == "" {
		bgColor = "#0a0e1a"
	}
	if bgElevated == "" {
		bgElevated = "#0f172a"
	}
	if bgSubtle == "" {
		bgSubtle = "#1e293b"
	}
	if fgColor == "" {
		fgColor = "#f1f5f9"
	}
	if fgMuted == "" {
		fgMuted = "#94a3b8"
	}
	if borderColor == "" {
		borderColor = "#334155"
	}
	if borderSubtle == "" {
		borderSubtle = "#1e293b"
	}
	if successColor == "" {
		successColor = "#10b981"
	}
	if warningColor == "" {
		warningColor = "#f59e0b"
	}
	if errorColor == "" {
		errorColor = "#ef4444"
	}

	// CSS custom properties for reference
	b.WriteString("/* Color Palette Variables */\n")
	b.WriteString(":root {\n")
	for _, c := range f.Colors {
		varName := fmt.Sprintf("--plexus-%s", normalizeID(c.ID))
		if opts.IncludeComments && c.Usage != "" {
			b.WriteString(fmt.Sprintf("  /* %s */\n", c.Usage))
		}
		b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, c.Value))
	}
	b.WriteString("}\n\n")

	// Dark mode (slate scheme) - primary scheme
	b.WriteString("/* MkDocs Material - Dark Mode (Slate) */\n")
	b.WriteString("[data-md-color-scheme=\"slate\"] {\n")
	b.WriteString(fmt.Sprintf("  --md-primary-fg-color: %s;\n", primaryColor))
	b.WriteString(fmt.Sprintf("  --md-primary-fg-color--light: %s;\n", primaryLight))
	b.WriteString(fmt.Sprintf("  --md-primary-fg-color--dark: %s;\n", primaryDark))
	b.WriteString(fmt.Sprintf("  --md-primary-bg-color: %s;\n", bgColor))
	b.WriteString(fmt.Sprintf("  --md-primary-bg-color--light: %s;\n", bgElevated))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("  --md-accent-fg-color: %s;\n", accentColor))
	b.WriteString(fmt.Sprintf("  --md-accent-fg-color--transparent: %s1a;\n", accentColor)) // 10% opacity
	b.WriteString(fmt.Sprintf("  --md-accent-bg-color: %s;\n", accentColor))
	b.WriteString(fmt.Sprintf("  --md-accent-bg-color--light: %s;\n", accentLight))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("  --md-default-fg-color: %s;\n", fgColor))
	b.WriteString(fmt.Sprintf("  --md-default-fg-color--light: %s;\n", fgMuted))
	b.WriteString(fmt.Sprintf("  --md-default-fg-color--lighter: %s9e;\n", fgColor))
	b.WriteString(fmt.Sprintf("  --md-default-fg-color--lightest: %s52;\n", fgColor))
	b.WriteString(fmt.Sprintf("  --md-default-bg-color: %s;\n", bgColor))
	b.WriteString(fmt.Sprintf("  --md-default-bg-color--light: %s;\n", bgElevated))
	b.WriteString(fmt.Sprintf("  --md-default-bg-color--lighter: %s;\n", bgSubtle))
	b.WriteString(fmt.Sprintf("  --md-default-bg-color--lightest: %s;\n", bgSubtle))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("  --md-code-fg-color: %s;\n", primaryLight))
	b.WriteString(fmt.Sprintf("  --md-code-bg-color: %s;\n", bgSubtle))
	b.WriteString(fmt.Sprintf("  --md-code-hl-color: %s26;\n", primaryColor)) // 15% opacity
	b.WriteString(fmt.Sprintf("  --md-code-hl-keyword-color: %s;\n", accentColor))
	b.WriteString(fmt.Sprintf("  --md-code-hl-function-color: %s;\n", primaryColor))
	b.WriteString(fmt.Sprintf("  --md-code-hl-string-color: %s;\n", successColor))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("  --md-typeset-color: %s;\n", fgColor))
	b.WriteString(fmt.Sprintf("  --md-typeset-a-color: %s;\n", primaryColor))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("  --md-footer-fg-color: %s;\n", fgColor))
	b.WriteString(fmt.Sprintf("  --md-footer-fg-color--light: %s;\n", fgMuted))
	b.WriteString(fmt.Sprintf("  --md-footer-bg-color: %s;\n", bgElevated))
	b.WriteString(fmt.Sprintf("  --md-footer-bg-color--dark: %s;\n", bgColor))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("  --md-admonition-fg-color: %s;\n", fgColor))
	b.WriteString(fmt.Sprintf("  --md-admonition-bg-color: %s;\n", bgElevated))
	b.WriteString(fmt.Sprintf("  --md-typeset-table-color: %s;\n", borderColor))
	b.WriteString("}\n\n")

	// Light mode (default scheme)
	b.WriteString("/* MkDocs Material - Light Mode */\n")
	b.WriteString("[data-md-color-scheme=\"default\"] {\n")
	b.WriteString(fmt.Sprintf("  --md-primary-fg-color: %s;\n", primaryDark))
	b.WriteString(fmt.Sprintf("  --md-primary-fg-color--light: %s;\n", primaryColor))
	b.WriteString("  --md-primary-bg-color: #ffffff;\n")
	b.WriteString("  --md-primary-bg-color--light: #f8fafc;\n")
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("  --md-accent-fg-color: %s;\n", accentColor))
	b.WriteString(fmt.Sprintf("  --md-accent-fg-color--transparent: %s1a;\n", accentColor))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("  --md-code-fg-color: %s;\n", primaryDark))
	b.WriteString("  --md-code-bg-color: #f1f5f9;\n")
	b.WriteString(fmt.Sprintf("  --md-typeset-a-color: %s;\n", primaryDark))
	b.WriteString("}\n\n")

	// Typography
	if f.Typography != nil && len(f.Typography.FontFamilies) > 0 {
		b.WriteString("/* Typography */\n")
		b.WriteString(":root {\n")
		for _, ff := range f.Typography.FontFamilies {
			fontValue := ff.Stack
			if fontValue == "" {
				fontValue = ff.Value
			}
			switch ff.ID {
			case "sans":
				b.WriteString(fmt.Sprintf("  --md-text-font: %s;\n", fontValue))
			case "mono":
				b.WriteString(fmt.Sprintf("  --md-code-font: %s;\n", fontValue))
			}
		}
		b.WriteString("}\n\n")
	}

	// Custom styles
	b.WriteString("/* Custom Styles */\n\n")

	b.WriteString("/* Header styling */\n")
	b.WriteString("[data-md-color-scheme=\"slate\"] .md-header {\n")
	b.WriteString(fmt.Sprintf("  background: linear-gradient(135deg, %s 0%%, %s 100%%);\n", bgColor, bgElevated))
	b.WriteString(fmt.Sprintf("  border-bottom: 1px solid %s;\n", borderSubtle))
	b.WriteString("}\n\n")

	b.WriteString("/* Navigation hover */\n")
	b.WriteString("[data-md-color-scheme=\"slate\"] .md-nav__link:hover {\n")
	b.WriteString(fmt.Sprintf("  color: %s;\n", primaryColor))
	b.WriteString("}\n\n")

	b.WriteString("[data-md-color-scheme=\"slate\"] .md-nav__link--active {\n")
	b.WriteString(fmt.Sprintf("  color: %s;\n", primaryColor))
	b.WriteString("  font-weight: 500;\n")
	b.WriteString("}\n\n")

	b.WriteString("/* Code blocks */\n")
	b.WriteString(".md-typeset code {\n")
	b.WriteString("  border-radius: 4px;\n")
	b.WriteString("  padding: 0.1em 0.3em;\n")
	b.WriteString("}\n\n")

	b.WriteString(".md-typeset pre > code {\n")
	b.WriteString("  border-radius: 8px;\n")
	b.WriteString("}\n\n")

	b.WriteString("/* Tables */\n")
	b.WriteString("[data-md-color-scheme=\"slate\"] .md-typeset table:not([class]) {\n")
	b.WriteString(fmt.Sprintf("  border: 1px solid %s;\n", borderColor))
	b.WriteString("  border-radius: 8px;\n")
	b.WriteString("  overflow: hidden;\n")
	b.WriteString("}\n\n")

	b.WriteString("[data-md-color-scheme=\"slate\"] .md-typeset table:not([class]) th {\n")
	b.WriteString(fmt.Sprintf("  background-color: %s;\n", bgSubtle))
	b.WriteString(fmt.Sprintf("  border-bottom: 1px solid %s;\n", borderColor))
	b.WriteString("}\n\n")

	b.WriteString("/* Admonitions */\n")
	b.WriteString("[data-md-color-scheme=\"slate\"] .md-typeset .admonition,\n")
	b.WriteString("[data-md-color-scheme=\"slate\"] .md-typeset details {\n")
	b.WriteString("  border-radius: 8px;\n")
	b.WriteString(fmt.Sprintf("  border: 1px solid %s;\n", borderSubtle))
	b.WriteString("}\n\n")

	b.WriteString("[data-md-color-scheme=\"slate\"] .md-typeset .admonition.info {\n")
	b.WriteString(fmt.Sprintf("  border-left-color: %s;\n", primaryColor))
	b.WriteString("}\n\n")

	b.WriteString("[data-md-color-scheme=\"slate\"] .md-typeset .admonition.tip {\n")
	b.WriteString(fmt.Sprintf("  border-left-color: %s;\n", accentColor))
	b.WriteString("}\n\n")

	b.WriteString("[data-md-color-scheme=\"slate\"] .md-typeset .admonition.warning {\n")
	b.WriteString(fmt.Sprintf("  border-left-color: %s;\n", warningColor))
	b.WriteString("}\n\n")

	b.WriteString("[data-md-color-scheme=\"slate\"] .md-typeset .admonition.danger {\n")
	b.WriteString(fmt.Sprintf("  border-left-color: %s;\n", errorColor))
	b.WriteString("}\n\n")

	b.WriteString("/* Search */\n")
	b.WriteString("[data-md-color-scheme=\"slate\"] .md-search__input {\n")
	b.WriteString(fmt.Sprintf("  background-color: %s;\n", bgSubtle))
	b.WriteString(fmt.Sprintf("  border: 1px solid %s;\n", borderColor))
	b.WriteString("}\n\n")

	b.WriteString("[data-md-color-scheme=\"slate\"] .md-search__input::placeholder {\n")
	b.WriteString(fmt.Sprintf("  color: %s;\n", fgMuted))
	b.WriteString("}\n\n")

	b.WriteString("/* Tabs */\n")
	b.WriteString("[data-md-color-scheme=\"slate\"] .md-typeset .tabbed-labels > label:hover {\n")
	b.WriteString(fmt.Sprintf("  color: %s;\n", primaryColor))
	b.WriteString("}\n\n")

	b.WriteString("[data-md-color-scheme=\"slate\"] .md-typeset .tabbed-labels > .tabbed-label--active {\n")
	b.WriteString(fmt.Sprintf("  color: %s;\n", primaryColor))
	b.WriteString("}\n\n")

	b.WriteString("/* Links */\n")
	b.WriteString("[data-md-color-scheme=\"slate\"] .md-typeset a:hover {\n")
	b.WriteString(fmt.Sprintf("  color: %s;\n", primaryLight))
	b.WriteString("}\n")

	return b.String(), nil
}

// Helper functions for writing tokens

func writeColorToken(b *strings.Builder, c ColorToken, opts CSSGeneratorOptions) {
	if opts.IncludeComments && c.Usage != "" {
		b.WriteString(fmt.Sprintf("  /* %s */\n", c.Usage))
	}
	varName := fmt.Sprintf("--color-%s", normalizeID(c.ID))
	b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, c.Value))
}

func writeFontFamily(b *strings.Builder, ff FontFamily, opts CSSGeneratorOptions) {
	if opts.IncludeComments && ff.Usage != "" {
		b.WriteString(fmt.Sprintf("  /* %s */\n", ff.Usage))
	}
	varName := fmt.Sprintf("--font-%s", normalizeID(ff.ID))
	// Use Stack if available, fall back to Value for backwards compatibility
	fontValue := ff.Stack
	if fontValue == "" {
		fontValue = ff.Value
	}
	b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, fontValue))
}

func writeFontSize(b *strings.Builder, fs FontSize, _ CSSGeneratorOptions) {
	varName := fmt.Sprintf("--text-%s", normalizeID(fs.ID))
	b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, fs.Value))
}

func writeFontWeight(b *strings.Builder, fw FontWeight, _ CSSGeneratorOptions) {
	varName := fmt.Sprintf("--font-weight-%s", normalizeID(fw.ID))
	b.WriteString(fmt.Sprintf("  %s: %d;\n", varName, fw.Value))
}

func writeLineHeight(b *strings.Builder, lh LineHeight, _ CSSGeneratorOptions) {
	varName := fmt.Sprintf("--leading-%s", normalizeID(lh.ID))
	b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, lh.Value))
}

func writeSpacing(b *strings.Builder, s SpacingToken, _ CSSGeneratorOptions) {
	varName := fmt.Sprintf("--spacing-%s", normalizeID(s.ID))
	b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, s.Value))
}

func writeBorderRadius(b *strings.Builder, br BorderRadiusToken, _ CSSGeneratorOptions) {
	varName := fmt.Sprintf("--radius-%s", normalizeID(br.ID))
	b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, br.Value))
}

func writeElevation(b *strings.Builder, e ElevationToken, opts CSSGeneratorOptions) {
	if opts.IncludeComments && e.Usage != "" {
		b.WriteString(fmt.Sprintf("  /* %s */\n", e.Usage))
	}
	varName := fmt.Sprintf("--shadow-%s", normalizeID(e.ID))
	b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, e.Value))
}

func writeDuration(b *strings.Builder, d DurationToken, opts CSSGeneratorOptions) {
	if opts.IncludeComments && d.Usage != "" {
		b.WriteString(fmt.Sprintf("  /* %s */\n", d.Usage))
	}
	varName := fmt.Sprintf("--duration-%s", normalizeID(d.ID))
	b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, d.Value))
}

func writeEasing(b *strings.Builder, e EasingToken, opts CSSGeneratorOptions) {
	if opts.IncludeComments && e.Usage != "" {
		b.WriteString(fmt.Sprintf("  /* %s */\n", e.Usage))
	}
	varName := fmt.Sprintf("--ease-%s", normalizeID(e.ID))
	b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, e.Value))
}

func writeBreakpoint(b *strings.Builder, bp Breakpoint, _ CSSGeneratorOptions) {
	varName := fmt.Sprintf("--breakpoint-%s", normalizeID(bp.ID))
	b.WriteString(fmt.Sprintf("  %s: %s;\n", varName, bp.MinWidth))
}

func writeZIndex(b *strings.Builder, z ZIndexToken, opts CSSGeneratorOptions) {
	if opts.IncludeComments && z.Usage != "" {
		b.WriteString(fmt.Sprintf("  /* %s */\n", z.Usage))
	}
	varName := fmt.Sprintf("--z-%s", normalizeID(z.ID))
	b.WriteString(fmt.Sprintf("  %s: %d;\n", varName, z.Value))
}

// normalizeID converts token IDs to CSS-friendly format.
func normalizeID(id string) string {
	// Replace underscores with hyphens, lowercase
	return strings.ToLower(strings.ReplaceAll(id, "_", "-"))
}

func cssVarName(category, id, prefix string) string {
	if prefix != "" {
		return fmt.Sprintf("--%s-%s-%s", prefix, category, normalizeID(id))
	}
	return fmt.Sprintf("--%s-%s", category, normalizeID(id))
}

func scssVarName(category, id, prefix string) string {
	if prefix != "" {
		return fmt.Sprintf("$%s-%s-%s", prefix, category, normalizeID(id))
	}
	return fmt.Sprintf("$%s-%s", category, normalizeID(id))
}

// isEmpty checks if Foundations has any tokens defined.
func (f Foundations) isEmpty() bool {
	return len(f.Colors) == 0 &&
		f.Typography == nil &&
		f.Spacing == nil &&
		len(f.Elevation) == 0 &&
		f.Motion == nil &&
		f.Grid == nil &&
		len(f.Breakpoints) == 0 &&
		len(f.BorderRadius) == 0 &&
		len(f.BorderWidth) == 0 &&
		len(f.Opacity) == 0 &&
		len(f.ZIndex) == 0
}

// modeValue returns the token's value for the given mode, falling back to
// the base value.
func modeValue(c ColorToken, mode string) string {
	if v := c.EffectiveModes()[mode]; v != "" {
		return v
	}
	return c.Value
}

// collectModes returns the sorted union of the document's declared modes and
// the modes present on color tokens.
func (ds *DesignSystem) collectModes() []string {
	set := map[string]bool{}
	for _, m := range ds.Modes {
		set[m] = true
	}
	for _, c := range ds.Foundations.Colors {
		for m := range c.EffectiveModes() {
			set[m] = true
		}
	}
	modes := make([]string, 0, len(set))
	for m := range set {
		modes = append(modes, m)
	}
	sort.Strings(modes)
	return modes
}

// densityVarName is the density scale custom property (--density, or
// prefixed --<prefix>-density).
func densityVarName(prefix string) string {
	if prefix != "" {
		return "--" + prefix + "-density"
	}
	return "--density"
}

// writeCSSModeBlocks emits one [data-mode="<m>"] override block per mode for
// every color token carrying a value in that mode. colorVar maps a token ID
// to its custom-property name for the active format.
func (ds *DesignSystem) writeCSSModeBlocks(b *strings.Builder, colorVar func(id string) string) {
	modes := ds.collectModes()
	if len(modes) == 0 {
		return
	}
	for _, mode := range modes {
		var lines []string
		for _, c := range ds.Foundations.Colors {
			if v, ok := c.EffectiveModes()[mode]; ok && v != "" {
				lines = append(lines, fmt.Sprintf("  %s: %s;\n", colorVar(c.ID), v))
			}
		}
		if len(lines) == 0 {
			continue
		}
		fmt.Fprintf(b, "\n[data-mode=%q] {\n", mode)
		for _, line := range lines {
			b.WriteString(line)
		}
		b.WriteString("}\n")
	}
}

// writeCSSDensityBlocks emits the base density scale property and one
// [data-density="<id>"] block per density variant (scale plus any spacing
// overrides). spacingVar maps a spacing token ID to its custom-property
// name for the active format.
func (ds *DesignSystem) writeCSSDensityBlocks(b *strings.Builder, prefix string, spacingVar func(id string) string) {
	densities := ds.Foundations.Densities
	if len(densities) == 0 {
		return
	}
	dv := densityVarName(prefix)
	fmt.Fprintf(b, "\n/* Density */\n:root {\n  %s: 1;\n}\n", dv)
	for _, d := range densities {
		fmt.Fprintf(b, "\n[data-density=%q] {\n", d.ID)
		fmt.Fprintf(b, "  %s: %v;\n", dv, d.Scale)
		ids := make([]string, 0, len(d.SpacingOverrides))
		for id := range d.SpacingOverrides {
			ids = append(ids, id)
		}
		sort.Strings(ids)
		for _, id := range ids {
			fmt.Fprintf(b, "  %s: %s;\n", spacingVar(id), d.SpacingOverrides[id])
		}
		b.WriteString("}\n")
	}
}
